In [1]:
import numpy as np

# No. 1

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1[5] = 11
arr1

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

# No. 2

In [6]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# No. 3

In [16]:
arr3 = np.ones((5,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        if not (i == 0 or i == len(arr3)-1 or j == 0 or j == len(arr3[i])-1):
            arr3[i,j]=0
arr3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# No. 4

In [24]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
#  Access the [2, 1,1]
print(z[2,1,1])

2
