In [1]:
import numpy as np

# No. 1

In [17]:
arr1 = np.zeros((4,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
for i in range(len(arr1)):
    arr1[i] = np.arange(len(arr1[i]))
arr1

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [18]:
arr1 += np.arange(4)
arr1

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

# No. 2

In [35]:
x_axis = 4
y_axis = 4
size = x_axis*y_axis
arr2 = np.arange(size).reshape((x_axis,y_axis))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
result = np.hsplit(arr2, x_axis/2)
result

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]